"""
Automatically translated from C++ to Python

Original file: calculator.h
Module: calculator

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

#include<iostream>
using namespace std;

int main() {
    int num1, num2;
    char operation;
    
    cout << "Enter first number: ";
    cin >> num1;
    cout << "Enter operation: ";
    cin >> operation;
    cout << "Enter second number: ";
    cin >> num2;
    
    switch(operation) {
        case '+':
            cout << num1 + num2;
            break;
        case '-':
            cout << num1 - num2;
            break;
        case '*':
            cout << num1 * num2;
            break;
        case '/':
            if(num2 != 0)
                cout << num1 / num2;
            else
                cout << "Error! Division by zero.";
            break;
        default:
            cout << "Error! Invalid operation.";
    }
    
    return 0;
}
def main():
    num1 = int(input("Enter first number: "))
    operation = input("Enter operation: ")
    num2 = int(input("Enter second number: "))

    if operation == '+':
        print(num1 + num2)
    elif operation == '-':
        print(num1 - num2)
    elif operation == '*':
        print(num1 * num2)
    elif operation == '/':
        if num2 != 0:
            print(num1 / num2)
        else:
            print("Error! Division by zero.")
    else:
        print("Error! Invalid operation.")

if __name__ == "__main__":
    main()