"""
Automatically translated from C++ to Python

Original file: utils.h
Module: utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

As an AI, I need to see the actual C++ code that you want to translate to Python. Please provide the C++ code.