"""
Automatically translated from C++ to Python

Original file: utils.cpp
Module: utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

As an AI, I need the C++ code to be provided in order to translate it into Python. Could you please provide the C++ code you'd like to have translated?